DB_HOST = 'localhost'
DB_NAME = 'teleWallet'
DB_USER = 'postgres'
DB_PASSWORD = 'postgres'
DB_PORT = 5432

SECRET_KEY = 'dev'

SECURITY_PASSWORD_SALT = '86582850694720286975186064842214611289'
SECURITY_USERNAME_ENABLE = False
SECURITY_USERNAME_REQUIRED = False
SECURITY_REGISTERABLE = False
SECURITY_CONFIRMABLE = False
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL = False
SECURITY_TWO_FACTOR = False
SECURITY_TWO_FACTOR_REQUIRED = False
SECURITY_UNIFIED_SIGNIN = False
SECURITY_PASSWORDLESS = False

SQLALCHEMY_TRACK_MODIFICATIONS = False
