DB_HOST = 'localhost'
DB_NAME = 'teleWallet'
DB_USER = 'postgres'
DB_PASSWORD = 'postgres'
DB_PORT = 5432

SECRET_KEY = 'dev'

SECURITY_PASSWORD_SALT = '86582850694720286975186064842214611289'
SECURITY_USERNAME_ENABLE = True
SECURITY_USERNAME_REQUIRED = True
SECURITY_REGISTERABLE = True
SECURITY_CONFIRMABLE = False
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_EMAIL = False
SECURITY_SEND_PASSWORD_RESET_NOTICE_EMAIL = False

SQLALCHEMY_TRACK_MODIFICATIONS = False